# numpy for handling matrix in Codeit Machine running basics 

In [2]:
import numpy as np 


In [6]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2],
    [7, 5, 6]
])

A


array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [9]:
B = np.array([
    [0, 1],
    [-1, 3],
    [5, 2]
])

B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

In [10]:
C = np.random.rand(3,5)
C

array([[0.9065395 , 0.76216976, 0.63237124, 0.02313995, 0.81504454],
       [0.67732482, 0.2760086 , 0.13547188, 0.74802446, 0.83279083],
       [0.62447203, 0.8380768 , 0.53890684, 0.29555398, 0.34119215]])

In [11]:
type(C)

numpy.ndarray

In [12]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
print(A[0][2]) # 첫줄 3번째 A13 -> 0,2 -> 2 
print(A[0,2]) 
type(A[0,2])

2
2


numpy.int64

In [27]:
A = np.array([
    [0,1,-1],
    [1,2,3],
    [2,1,0],
    [-1,2,-4]
])
B = np.array([
    [0,2],
    [1,1],
    [-1,-2]
])

#정의한 행렬 A의 2 행 2열 원소에 접근해 보세요.
display(A)
print(A[1,1])

#정의한 행렬 A의 4 행 1열 원소에 접근해 보세요.
display(B)
print(A[3,0])

array([[ 0,  1, -1],
       [ 1,  2,  3],
       [ 2,  1,  0],
       [-1,  2, -4]])

2


array([[ 0,  2],
       [ 1,  1],
       [-1, -2]])

-1


-- 행렬의 덧샘과 곱샘 
A * B

NumPy에서 * 연산자는 요소별 곱셈을 수행해요. 
하지만 행렬곱은 @ 연산자를 사용하거나 np.dot() 함수를 사용해요. 따라서 모든 행렬 곱이 요소별 곱셈으로 동작하지는 않아요. 요소별 곱셈은 같은 위치의 요소들끼리 곱하는 연산이라, 두 행렬의 차원이 같아야 해요.

행렬 곱셈이 가능하려면 앞 행렬의 열 개수와 뒤 행렬의 행 개수가 같아야 합니다. 이때 결과 행렬의 크기는 앞 행렬의 행 개수 × 뒤 행렬의 열 개수가 됩니다

예> (m × n) 행렬 × (p × q) 행렬 
-->  n == p 숫자가 같으면 곱셈 가능
--> 곱의 차원 결과: m x q 


In [35]:
import numpy as np

A = np.array([
    [1, -1, 2],
    [3, 2, 2,],
    [ 4, 1, 2]
])

B = np.random.rand(3,3)

display(A),display(B)

display(A * 5)

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

array([[0.68989868, 0.38005671, 0.99111029],
       [0.89594559, 0.20360845, 0.57168205],
       [0.10795028, 0.2392166 , 0.46825621]])

array([[ 5, -5, 10],
       [15, 10, 10],
       [20,  5, 10]])

In [36]:
np.dot(A, B)

array([[0.00985365, 0.65488147, 1.35594065],
       [4.07748778, 2.02582025, 5.05320737],
       [3.87144087, 2.20226851, 5.4726356 ]])

In [37]:
A @ B

array([[0.00985365, 0.65488147, 1.35594065],
       [4.07748778, 2.02582025, 5.05320737],
       [3.87144087, 2.20226851, 5.4726356 ]])

In [38]:
A @ B + ( A + 2)

array([[3.00985365, 1.65488147, 5.35594065],
       [9.07748778, 6.02582025, 9.05320737],
       [9.87144087, 5.20226851, 9.4726356 ]])

In [53]:
# 행렬 4개 연산 연습
import numpy as np

A = np.array([
    [1, -1, 2],
    [3, 2, 2]
])

B = np.array([
    [0, 1],
    [-1, 1],
    [5, 2]
])

C = np.array([
    [2, -1],
    [-3, 3]
])

D = np.array([
    [-5, 1],
    [2, 0]
])

# 행렬 연산 결과를 result에 저장하세요
a = (2 * A) @ (-1 * B) 
result =  (2 * A) @ (-1 * B) @ (3*C + D)
result = 2*A @ -B @ (3*C + D)
# 테스트 코드
result



array([[  34,  -28],
       [ 110, -130]])

15. 전치 행렬, 단위 행렬, 역행렬

전치행렬 Transposed matrix:  행렬의 행과 열을 서로 바꾼 행렬을 의미합니다. 
- m×n 행렬의 전치행렬은 n×m 행렬이 되며, 기호로는 A^T로 나타냅니다. (대각선 기준 전환)
[[1, 2, 1],
 [3, 2, 2]
]
==>
[[1, 3]
 [2, 3]
 [1, 2]
]

단위행렬 Identity matrix : 주대각선 성분은 모두 1이고 나머지 성분은 모두 0인 정사각행렬 (정사각형 구조)
- 2 * 1 = 2 ==> 선형대수학에서 일반수학 1의 역활

혁행렬 Inverse matrix
- 10 * 1/10 = 1 , 5 * 1/5 = 1
- 곱했을 때 1이 나오도록 하는 수를 '역수'라고 하는데, 선형대수학에서는 역행렬이라고 한다. (정사각형 구조)


In [61]:
#종합해서 복잡한 행렬 연산을 numpy를 사용해서 계산

import numpy as np

A = np.array([
    [1, -1, 2],
    [3, 2, 2]
])

B = np.array([
    [0, 1],
    [-1, 1],
    [5, 2]
])

C = np.array([
    [2, -1],
    [-3, 3]
])

D = np.array([
    [-5, 1],
    [2, 0]
])

# B(T) x (2A(T)) x (3C(-1) + D(T))
# 행렬 연산을 result 변수에 저장하세요
result = B.T @ (2*A.T) @ (3* np.linalg.pinv(C) + D.T)
#result = B.T @ (2*A.T) @ (3*np.linalg.pinv(C) + D.T)

# 테스트 코드
result


array([[20., 98.],
       [56., 60.]])